add kms key creation to the flow
zalando-stups/sevenseconds pull request #65
Opened 2017-06-21 11:47 UTC by ideahitme

This PR adds kms key for each account if specified in the configuration. See our configuration for the pattern we will use:

```
  kms:
    my_key_alias:
      tags:
      - my_tag_key: my_tag_value

```

2017-06-21 11:56 UTC, szuecs commented
@tuxlife I already reviewed, maybe you want to at it, too.
:+1:

2017-06-21 12:33 UTC, tuxlife requested changes

2017-06-21 12:33 UTC, tuxlife commented on sevenseconds/config/kms.py
> +                    Description='key used by deployment pipeline for secret encryption/decryption',
Please get the description from the configurations file like the tags

2017-06-21 12:33 UTC, tuxlife commented on sevenseconds/config/kms.py
> +                    return
why did you break the whole function and not only the loop, if you get an error?

2017-06-21 12:33 UTC, tuxlife commented on sevenseconds/config/kms.py
> +                    return
please skip only the current value in the loop and not the whole function

2017-06-21 15:33 UTC, ideahitme commented
@tuxlife I made quite a few changes, please take a look again (change the configuration.yaml as well)

2017-06-21 20:10 UTC, tuxlife approved these changes

2017-06-21 20:10 UTC, tuxlife commented
:+1:

2017-06-22 10:16 UTC, ideahitme commented
@tuxlife please take a look again

2017-06-22 10:18 UTC, tuxlife commented
:+1:

2017-06-22 10:19 UTC, tuxlife commented
Please use squash merge

2017-06-22 10:19 UTC, ideahitme commented
👍

2017-06-22 10:20 UTC, merged