Allow policy_arns to be attached, needed for AWS managed policies
zalando-stups/sevenseconds pull request #78
Opened 2018-08-29 14:49 UTC by msooszalando

This change is needed to correctly support AWS managed policies, see https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_managed-vs-inline.html?shortFooter=true#aws-managed-policies for such policies. They are very useful and lower the burden of maintenance of policy documents.

2018-09-12 08:31 UTC, szuecs commented
@msooszalando please add your signature in the comment of your PR `git commit -s` and rebase to one commit.

@sarnowski is this the change you talked about with me some days ago?

2018-09-12 08:38 UTC, szuecs requested changes
the TODO needs to be fixed

2018-09-12 08:38 UTC, szuecs commented on sevenseconds/config/iam.py
> +                    # TODO make policy optional
Can you fix the TODO, before the merge?

2021-04-16 11:54 UTC, mikkeloscar commented
Managed policies are now supported since #108 Closing this!

2021-04-16 11:54 UTC, closed without merging

2021-04-19 08:04 UTC, msooszalando commented
Woooow! Yaaaay! :heart_eyes: